default: &default
  adapter: postgresql
  encoding: unicode
  host: 172.17.0.2
  user: postgres
  password: 123456
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: photo_app_development

test:
  <<: *default
  database: photo_app_test

production:
  <<: *default
  database: photo_app_production
  username: photo_app
  password: <%= ENV['PHOTO_APP_DATABASE_PASSWORD'] %>
