default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: photo_app_development

test:
  <<: *default
  database: photo_app_test

production:
  <<: *default
  database: photo_app_production
  username: photo_app
  password: <%= ENV['PHOTO_APP_DATABASE_PASSWORD'] %>
